apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pgvector-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/rancher/k3s/storage/postgresql-pgvector-manual
