apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pgvector-pvc
  namespace: sejm-whiz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: postgresql-pgvector-pv
