[project]
name = "sejm-whiz"
version = "0.1.0"
description = "Process data exposed by the Sejm (Polish parliament) API then..."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["polylith-cli>=1.30.1"]

[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]
