# GPU-enabled deployment based on working k3s-docker-gpu example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejm-whiz-processor-gpu
  namespace: sejm-whiz
  labels:
    app: sejm-whiz-processor-gpu
    version: gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sejm-whiz-processor-gpu
  template:
    metadata:
      labels:
        app: sejm-whiz-processor-gpu
        version: gpu
    spec:
      runtimeClassName: nvidia  # Direct NVIDIA runtime access
      nodeSelector:
        gpu: gtx1060  # Target GPU node
      containers:
      - name: processor
        image: sejm-whiz-processor:optimized
        env:
        # NVIDIA GPU environment variables (from working example)
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        # Database connection
        - name: DATABASE_HOST
          value: "postgresql-pgvector.sejm-whiz"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "sejm_whiz"
        - name: DATABASE_USER
          value: "sejm_whiz_user"
        - name: DATABASE_PASSWORD
          value: "sejm_whiz_password"
        # Redis connection
        - name: REDIS_HOST
          value: "redis.sejm-whiz"
        - name: REDIS_PORT
          value: "6379"
        # Application-specific environment
        - name: EMBEDDING_DEVICE
          value: "cuda"
        - name: EMBEDDING_MODEL_CACHE_DIR
          value: "/app/.cache"
        - name: HF_HOME
          value: "/app/.cache"
        - name: TRANSFORMERS_CACHE
          value: "/app/.cache"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
            # nvidia.com/gpu: 1  # Temporarily disabled until NVIDIA Container Toolkit is properly configured
          limits:
            memory: "6Gi"
            cpu: "3"
            # nvidia.com/gpu: 1  # Temporarily disabled until NVIDIA Container Toolkit is properly configured
        volumeMounts:
        - name: model-cache
          mountPath: /app/.cache
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: sejm-whiz-model-cache
---
apiVersion: v1
kind: Service
metadata:
  name: sejm-whiz-processor-gpu
  namespace: sejm-whiz
  labels:
    app: sejm-whiz-processor-gpu
spec:
  selector:
    app: sejm-whiz-processor-gpu
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
