apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sejm-whiz-model-cache
  namespace: sejm-whiz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
