# WIP: Job-based processor deployment - under development
apiVersion: batch/v1
kind: Job
metadata:
  name: sejm-whiz-processor-job
  namespace: sejm-whiz
  labels:
    app: sejm-whiz-processor
    version: gpu
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: sejm-whiz-processor
        version: gpu
    spec:
      restartPolicy: Never
      runtimeClassName: nvidia  # Direct NVIDIA runtime access
      nodeSelector:
        gpu: gtx1060  # Target GPU node
      containers:
      - name: processor
        image: sejm-whiz-processor:optimized
        env:
        # NVIDIA GPU environment variables
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        # Deployment environment
        - name: DEPLOYMENT_ENV
          value: "k3s"
        # Database connection
        - name: DATABASE_HOST
          value: "postgresql-pgvector.sejm-whiz"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "sejm_whiz"
        - name: DATABASE_USER
          value: "sejm_whiz_user"
        - name: DATABASE_PASSWORD
          value: "sejm_whiz_password"
        - name: DATABASE_SSL_MODE
          value: "disable"
        # Redis connection
        - name: REDIS_HOST
          value: "redis.sejm-whiz"
        - name: REDIS_PORT
          value: "6379"
        # Application-specific environment
        - name: EMBEDDING_DEVICE
          value: "cuda"
        - name: EMBEDDING_MODEL_CACHE_DIR
          value: "/app/.cache"
        - name: HF_HOME
          value: "/app/.cache"
        - name: TRANSFORMERS_CACHE
          value: "/app/.cache"
        resources:
          requests:
            memory: "4Gi"  # Increased for ML dependencies
            cpu: "2"
          limits:
            memory: "8Gi"  # Increased for ML dependencies
            cpu: "4"
        volumeMounts:
        - name: model-cache
          mountPath: /app/.cache
        - name: source-code
          mountPath: /app
        - name: components
          mountPath: /app/components
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: sejm-whiz-model-cache
      - name: source-code
        hostPath:
          path: /tmp/sejm-whiz
          type: DirectoryOrCreate
      - name: components
        hostPath:
          path: /tmp/sejm-whiz/components
          type: Directory
