# PostgreSQL with pgvector configuration for k3s deployment
postgresql:
  image:
    repository: pgvector/pgvector
    tag: pg17
    pullPolicy: IfNotPresent

  auth:
    database: sejm_whiz
    username: sejm_whiz_user
    password: sejm_whiz_password
    postgresPassword: postgres_admin_password

  ssl:
    enabled: true
    certificatesSecret: ""
    certFilename: ""
    certKeyFilename: ""

  primary:
    persistence:
      enabled: true
      storageClass: "local-path"  # k3s default storage class
      size: 10Gi

    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

    initdb:
      scripts:
        01-create-extensions.sql: |
          CREATE EXTENSION IF NOT EXISTS vector;
          CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        02-create-indexes.sql: |
          -- Will be populated by migrations

  service:
    type: ClusterIP
    port: 5432

  metrics:
    enabled: false

# k3s specific configuration
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - p7
